apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-ocean
spec:
  displayName: Ocean
  author:
    name: 凌霞软件
    website: https://www.lxware.cn
  description: 知识库类型主题
  logo: https://www.halo.run/logo
  homepage: https://www.halo.run/store/apps/app-OBDIu
  repo: https://github.com/lxware-dev/theme-ocean.git
  issues: https://github.com/lxware-dev/theme-ocean/issues
  settingName: "theme-ocean-setting"
  configMapName: "theme-ocean-configMap"
  version: 1.5.1
  requires: ">=2.21.0"
  license:
    - name: "GNU General Public License v3.0"
      url: "https://github.com/lxware-dev/theme-ocean/blob/master/LICENSE"
